### PR TITLE
Create py.typed and turn on mypy strict mode

### PR DESCRIPTION
**Pull request by DanielNoord**
😄

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Well, it's nice that it's that easy 😄 Thanks!

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Is `mypy` run in CI? Otherwise you might want to check if `strict` actually passes locally

**Comment by Pierre-Sassoulas** [comment]
Hmm, it look like I did not activate the pre-commit bot.

**Comment by Pierre-Sassoulas** [comment]
All right, this need some work.

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you Daniel !

**Pull request merged**
